[application]
name = "cAssets dToken Wrapper"
default_platform = "web"

[web.app]
title = "cAssets dToken Wrapper"
base_path = "cAssets_dToken_wrapper"
## keeps CSP happy
csp_hash = true
## avoids SWC minifier errors
minify_js = false

[web.wasm]
## ensures WASM + JS are together
mode = "bundled"
## forces Dioxus to generate the snippets/ folder for wasm-bindgen helpers
## snippets = true